export const BET_STATUS = {
  REQUEST_BET_STATUS: 'REQUEST_BET_STATUS',
  RECEIVE_BET_STATUS: 'RECEIVE_BET_STATUS',
  SELECT_BET_TYPE: 'SELECT_BET_TYPE',
  INVALIDATE_BET_TYPE: 'INVALIDATE_BET_TYPE',
  REQUEST_UPDATE_BET_CONTENT: 'UPDATE_BET_CONTENT',
  COMPLETE_UPDATE_BET_CONTENT: 'COMPLETE_UPDATE_CONTENT',
};

export const LOGIN = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
};

export const BET_NOTIFICATION = {
  ADD_CHANNEL: 'ADD_CHANNEL',
  RECEIVE_RESULT: 'RECEIVE_RESULT',
};
